/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AaveRentEscrowInterface extends Interface {
    getFunction(nameOrSignature: "aToken" | "aavePool" | "confirmLease" | "confirmed" | "deadline" | "depositAmount" | "getAccruedYield" | "getAverageRating" | "getNumRatings" | "getTotalAaveBalance" | "landlord" | "numRatings" | "rateLandlord" | "refund" | "releaseFunds" | "tenant" | "totalRating" | "weth"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Confirmed" | "Deposited" | "Rated" | "Refunded" | "Released" | "SuppliedToAave"): EventFragment;

    encodeFunctionData(functionFragment: 'aToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'aavePool', values?: undefined): string;
encodeFunctionData(functionFragment: 'confirmLease', values?: undefined): string;
encodeFunctionData(functionFragment: 'confirmed', values?: undefined): string;
encodeFunctionData(functionFragment: 'deadline', values?: undefined): string;
encodeFunctionData(functionFragment: 'depositAmount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAccruedYield', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAverageRating', values?: undefined): string;
encodeFunctionData(functionFragment: 'getNumRatings', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTotalAaveBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'landlord', values?: undefined): string;
encodeFunctionData(functionFragment: 'numRatings', values?: undefined): string;
encodeFunctionData(functionFragment: 'rateLandlord', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'refund', values?: undefined): string;
encodeFunctionData(functionFragment: 'releaseFunds', values?: undefined): string;
encodeFunctionData(functionFragment: 'tenant', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalRating', values?: undefined): string;
encodeFunctionData(functionFragment: 'weth', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'aToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'aavePool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmLease', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deadline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAccruedYield', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAverageRating', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getNumRatings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalAaveBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'landlord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'numRatings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rateLandlord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseFunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tenant', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRating', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'weth', data: BytesLike): Result;
  }

  
    export namespace ConfirmedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositedEvent {
      export type InputTuple = [from: AddressLike, value: BigNumberish];
      export type OutputTuple = [from: string, value: bigint];
      export interface OutputObject {from: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RatedEvent {
      export type InputTuple = [by: AddressLike, score: BigNumberish];
      export type OutputTuple = [by: string, score: bigint];
      export interface OutputObject {by: string, score: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundedEvent {
      export type InputTuple = [value: BigNumberish];
      export type OutputTuple = [value: bigint];
      export interface OutputObject {value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReleasedEvent {
      export type InputTuple = [landlordAmount: BigNumberish, tenantYield: BigNumberish];
      export type OutputTuple = [landlordAmount: bigint, tenantYield: bigint];
      export interface OutputObject {landlordAmount: bigint, tenantYield: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SuppliedToAaveEvent {
      export type InputTuple = [amount: BigNumberish];
      export type OutputTuple = [amount: bigint];
      export interface OutputObject {amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AaveRentEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): AaveRentEscrow;
    waitForDeployment(): Promise<this>;

    interface: AaveRentEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    aToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    aavePool: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    confirmLease: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    confirmed: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    deadline: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    depositAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getAccruedYield: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getAverageRating: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getNumRatings: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getTotalAaveBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    landlord: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    numRatings: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    rateLandlord: TypedContractMethod<
      [score: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    refund: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    releaseFunds: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    tenant: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalRating: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    weth: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'aToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'aavePool'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'confirmLease'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'confirmed'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'deadline'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'depositAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAccruedYield'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAverageRating'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getNumRatings'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalAaveBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'landlord'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'numRatings'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rateLandlord'): TypedContractMethod<
      [score: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'refund'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseFunds'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tenant'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalRating'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'weth'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'Confirmed'): TypedContractEvent<ConfirmedEvent.InputTuple, ConfirmedEvent.OutputTuple, ConfirmedEvent.OutputObject>;
getEvent(key: 'Deposited'): TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
getEvent(key: 'Rated'): TypedContractEvent<RatedEvent.InputTuple, RatedEvent.OutputTuple, RatedEvent.OutputObject>;
getEvent(key: 'Refunded'): TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
getEvent(key: 'Released'): TypedContractEvent<ReleasedEvent.InputTuple, ReleasedEvent.OutputTuple, ReleasedEvent.OutputObject>;
getEvent(key: 'SuppliedToAave'): TypedContractEvent<SuppliedToAaveEvent.InputTuple, SuppliedToAaveEvent.OutputTuple, SuppliedToAaveEvent.OutputObject>;

    filters: {
      
      'Confirmed()': TypedContractEvent<ConfirmedEvent.InputTuple, ConfirmedEvent.OutputTuple, ConfirmedEvent.OutputObject>;
      Confirmed: TypedContractEvent<ConfirmedEvent.InputTuple, ConfirmedEvent.OutputTuple, ConfirmedEvent.OutputObject>;
    

      'Deposited(address,uint256)': TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
      Deposited: TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
    

      'Rated(address,uint256)': TypedContractEvent<RatedEvent.InputTuple, RatedEvent.OutputTuple, RatedEvent.OutputObject>;
      Rated: TypedContractEvent<RatedEvent.InputTuple, RatedEvent.OutputTuple, RatedEvent.OutputObject>;
    

      'Refunded(uint256)': TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
      Refunded: TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
    

      'Released(uint256,uint256)': TypedContractEvent<ReleasedEvent.InputTuple, ReleasedEvent.OutputTuple, ReleasedEvent.OutputObject>;
      Released: TypedContractEvent<ReleasedEvent.InputTuple, ReleasedEvent.OutputTuple, ReleasedEvent.OutputObject>;
    

      'SuppliedToAave(uint256)': TypedContractEvent<SuppliedToAaveEvent.InputTuple, SuppliedToAaveEvent.OutputTuple, SuppliedToAaveEvent.OutputObject>;
      SuppliedToAave: TypedContractEvent<SuppliedToAaveEvent.InputTuple, SuppliedToAaveEvent.OutputTuple, SuppliedToAaveEvent.OutputObject>;
    
    };
  }