/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'AaveRentEscrow', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AaveRentEscrow__factory>
getContractFactory(name: 'IPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IPool__factory>
getContractFactory(name: 'IWETH', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IWETH__factory>
getContractFactory(name: 'RentEscrow', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RentEscrow__factory>

  getContractAt(name: 'AaveRentEscrow', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AaveRentEscrow>
getContractAt(name: 'IPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IPool>
getContractAt(name: 'IWETH', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IWETH>
getContractAt(name: 'RentEscrow', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RentEscrow>

  deployContract(name: 'AaveRentEscrow', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AaveRentEscrow>
deployContract(name: 'IPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPool>
deployContract(name: 'IWETH', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IWETH>
deployContract(name: 'RentEscrow', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RentEscrow>

  deployContract(name: 'AaveRentEscrow', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AaveRentEscrow>
deployContract(name: 'IPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPool>
deployContract(name: 'IWETH', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IWETH>
deployContract(name: 'RentEscrow', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RentEscrow>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  